#!/bin/bash

alias gmaster="git master"
alias gpush="git push"
alias gpick="git cherry-pick"
alias gp="git pull"
alias gm="git merge"
alias gst="git status"
alias grmt="git remote"
alias gadd="git add"
alias gcmt="git commit"
alias gb="git branch"
alias gck="git checkout"
alias gsts="git stash"
alias gf="git fetch"
alias gt="git tag"
